# Enable the H2 database console in your browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Database connection settings
spring.datasource.url=jdbc:h2:mem:hoteldb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Show the SQL queries Spring executes in your terminal
spring.jpa.show-sql=true    

server.port=8008